baseURL = ''
languageCode = 'pl-PL'
title = 'Propaganda'
theme= "archie"
language = 'pl'

name = "Theme Name"
license = "MIT"
licenselink = "Link to theme's license"
min_version = "0.59.1"
copyright = "© JesterPawel"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"

paginate=4 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Naszą egzystencję da się zaprogramować"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	twitter = "Uuhuuu"
	favicon = "/logo3.png"
	description = "Zrozum mechanikę działania współczesnego świata. Naucz się rozszyfrowywać dezinformację i propagandę. Uzyskaj wgląd w psychologię ludzką, system finansowy. "
	homepage = "Homepage description"
	tags = ["informacje,", "news,", "finanse,", "psychologia"]
	robots = "index, follow"
	name = "Paweł Łajewski"
	lang = "pl"

# Social Tags

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/JesterPawel"

[[params.social]]
name = "Youtube"
icon = "youtube"
url = "https://www.youtube.com/@uuhuu"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/nieznanypodlasianin/"

[[params.social]]
name = "Jester's Music"
icon = "music"
url = "https://uuhuuu.github.io/"


# Main menu Items

[[menu.main]]
name = "Główna"
url = "/"
weight = 1

[[menu.main]]
name = "Wpisy"
url = "/posts"
weight = 2

[[menu.main]]
name = "Info"
url = "/about"
weight = 3

[[menu.main]]
name = "Tagi"
url = "/tags"
weight = 4